### ISSUE TITLE
Было бы круто добавить выбор дат для графиков

### ISSUE THREAD

**Issue by Edgidze** [efradkin/some_moex#24]

**Comment by Edgidze** [comment]
![изображение](https://github.com/efradkin/some_moex/assets/86978925/cdbbdf8d-bbe3-4d3d-b2b4-1f9af91840a4)
было бы круто ещё и потому, что вот как будто для Яндекса например как будто через день-два после большого количества сделок за день акция расти начинает.

...но во-первых, временной период маленький, а во-вторых она и так почти всё время растёт.

**Comment by efradkin** [comment]
![image](https://github.com/efradkin/some_moex/assets/16664546/e4779adb-1d47-4d74-92a2-53341a89c9fa)
Done.
