### ISSUE TITLE
Ошибка для графика YNDX за первое марта

### ISSUE THREAD

**Issue by Edgidze** [efradkin/some_moex#30]
Нужно исправить ошибку: цена YNDX за первое марта различается при выборе лишь конечной даты отображения графика цен закрытия YNDX и выборе дат отображения с начала года до сегодня.

**Comment by Edgidze** [comment]
![изображение](https://github.com/efradkin/some_moex/assets/86978925/01415adf-1fc4-4681-8416-84120893e950)
![изображение](https://github.com/efradkin/some_moex/assets/86978925/6c3cd53e-0a9e-4cd2-92e9-7d912d4795bf)

**Comment by efradkin** [comment]
Похоже, диаграмма не может переварить так много узлов. Я уменьшил лимит с 1000 до 300.
